#   The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#   1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#   Let us list the factors of the first seven triangle numbers:
#       1: 1
#       3: 1,3
#       6: 1,2,3,6
#       10: 1,2,5,10
#       15: 1,3,5,15
#       21: 1,3,7,21
#       28: 1,2,4,7,14,28
#   We can see that 28 is the first triangle number to have over five divisors.
#   What is the value of the first triangle number to have over five hundred divisors?

def div(num):
    n = int(num*(num+1)/2)
    c = 0
    s = 1
    while n % 2 == 0:
        n = n / 2
        c += 1
    s += c
    i = 3
    while n != 1:
        c = 0
        while n % i == 0:
            n = n/i
            c += 1
        s *= c + 1
        i += 2
    return s

i = 10000

while div(i) <= 500:
    i += 1
print(int(i*(i+1)/2))
