# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are: 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

import math

p = []

for i in range(1, 10000):
        p.append(int(i * (3 * i - 1) / 2))

min = p[len(p) - 1]

for i in range(len(p)):
        for j in range(i + 1, len(p)):
                n = p[i] + p[j]
                x = (1 + math.sqrt(1 + 24 * n)) / 6
                if x == int(x):
                        n = p[j] - p[i]
                        if n < min:
                                x = (1 + math.sqrt(1 + 24 * n)) / 6
                                if x == int(x):
                                        min = n

print(min)